### ISSUE TITLE
Write RSpec tests

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/request_info#1]
There're currently no tests which makes this code base automatically legacy.

Write RSpec tests to cover as much as possible.

**Comment by skalee** [comment]
@ribose-jeffreylau @ronaldtse What are minimum Ruby & Rails versions? Ruby 2.2+ and Rails 5+ (4+ if easy)? Currently, gemspec says Rails 3.1+, but I guess it's just outdated.

**Comment by ronaldtse** [comment]
Yes it’s outdated, Rails 4+ is good, thanks!

**Comment by skalee** [comment]
I believe this one can be marked as done. If there is anything more to do, it should go in a separate issue.
