### ISSUE TITLE
IP spoofing issues

### ISSUE THREAD

**Issue by skalee** [riboseinc/request_info#13]
As pointed out in [xyu.io blog](http://www.xyu.io/2013/07/proxies-ip-spoofing), and comments by @ribose-jeffreylau: https://github.com/riboseinc/request_info/blob/8a292bf151e1cc98bd49a6a139af2a2de52a09c4/lib/request_info/ip_detector.rb#L20-L38 it is easy to spoof IP and lie about client's location.

Currently, the best countermeasure is to rely on Rails' `ActionDispatch::RemoteIp` middleware. However, (again, as posted in above comments) it requires proper configuration to work correctly. Furthermore, whilst aforementioned middleware is an optional dependency, the gem may produce incorrect results without it, like returning a series of IPs instead of one.

- [x] Add README section about IP spoofing, and how to countermeasure it
- [x] Provide a more robust way of guessing client IP independent from `ActionDispatch::RemoteIp` middleware, or skip IP detection when this middleware is missing

**Comment by ronaldtse** [comment]
Agree!

**Comment by ribose-jeffreylau** [comment]
Thanks @skalee !

(Although I can't take credits for the above comments --- I was only responsible for uploading the code :)

**Comment by skalee** [comment]
IMHO actually there is no need for a README warning. Maybe some short note that one should check out docs for `ActionDispatch::RemoteIp` before using it, which has been added in #42.

**Comment by skalee** [comment]
Since everything else is long done, I am closing this issue.
