### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by skalee** [riboseinc/request_info#35]
Attach some service for test coverage measurement. I suppose CodeCov. Note that there's a Coverity badge in README, but I doubt it was ever working right. I'll replace it with CodeCov badge (or another respective one) when coverage is available for this project.

**Comment by skalee** [comment]
@ronaldtse Could you enable CodeCov for this project (or another code coverage tool like Coverity)?

**Comment by skalee** [comment]
@ronaldtse?

**Comment by ribose-jeffreylau** [comment]
Hi @skalee , @ronaldtse already sent you an email.  Thanks!

**Comment by ronaldtse** [comment]
@skalee all good here?

**Comment by skalee** [comment]
@ronaldtse I saw your e-mail but I don't know what to do with token I saw. First of all, I'm not sure it's for CodeCov or Coverity. The former never required any tokens (it was just a matter of enabling it). The latter is more difficult — coverity.com now redirects to synopsys.com (acquisition?) and I can't find any hosted code coverage solution on that page.

**Comment by ronaldtse** [comment]
It's actually the CodeCov token. Do you have access to this page? https://codecov.io/gh/riboseinc/request_info

**Comment by skalee** [comment]
My bad, you're right. I forgot to add the CodeCov gem, that's all.

**Comment by skalee** [comment]
Fixed in #44.
