### ISSUE TITLE
What is the purpose of LocaleNameMap?

### ISSUE THREAD

**Issue by skalee** [riboseinc/request_info#38]
There is a class named `RequestInfo::LocaleNameMap`. It is never referenced, neither it was before my first commit in this project. I am going to delete it, but perhaps it's for some work-in-progress feature?

**Comment by ronaldtse** [comment]
@skalee this was for detecting the default locale (language - script) of the IP address; if we can revive it that would be great.

**Comment by skalee** [comment]
@ronaldtse this is handled by similar class `RequestInfo::CountryLocaleMap`.

We determine country basing on IP address, and then use country -> locale mapping in `RequestInfo::CountryLocaleMap` to obtain default locale for given country (see [CSV](https://github.com/riboseinc/request_info/blob/6dce17bfeb15238381239f3a4d6fa10aa9ec4870/data/country_locale_map.csv)).

This issue is about `RequestInfo::LocaleNameMap` which maps locale code to language name in English and in matching language, and which we do not use (see [CSV](https://github.com/riboseinc/request_info/blob/6dce17bfeb15238381239f3a4d6fa10aa9ec4870/data/locale_name_map.csv)).

**Comment by ronaldtse** [comment]
@skalee I got confused -- yes this might not be very useful in the gem. Maybe we should just create a new repo to store data like this, say, in YAML or JSON?

**Comment by ronaldtse** [comment]
Just for the record, 
https://github.com/riboseinc/request_info/issues/51#issuecomment-413116581 is the answer to why this issue is no longer being tackled in this gem.
