### ISSUE TITLE
Consider extracting country-locale map into a separate gem

### ISSUE THREAD

**Issue by skalee** [riboseinc/request_info#39]
There is a class `RequestInfo::CountryLocaleMap` which provides mapping between countries and locales popular there. Let's consider moving that mapping into a separate gem as it is generally useful.

**Comment by skalee** [comment]
Also path to `data/country_locale_map.csv` is currently configurable. I don't see much sense in that — this file is entirely based on publicly available data, and should be maintained anyway if new country rises in the world. For simplicity sake, I want to remove this configuration setting when extracting the gem.

**Comment by ronaldtse** [comment]
@skalee agree!

**Comment by skalee** [comment]
The only issue I have here is that I'm not sure about licensing. According to this comment:

https://github.com/riboseinc/request_info/blob/5d1407fbb75bda401fb35b25718a6d4f8a0956eb/data/country_locale_map.csv#L1 the mapping is authored by Ribose basing on data from two sources:

- http://www.i18nguy.com/unicode/language-identifiers.html
- https://www.infoplease.com/languages-spoken-each-country-world

Both lists seem non-free. I am not sure if final document is a derivative work, and if it is okay to include it in MIT gem or not.

Alternatively, we could use https://www.cia.gov/library/publications/the-world-factbook/fields/2098.html which is in public domain, but it would require reworking this list which is a considerable amount of work (not a horrible hassle though).

cc @ronaldtse @ribose-jeffreylau

**Comment by ronaldtse** [comment]
The first link is quite comprehensive but is crucially missing the "priority", e.g., the China entry lists `bo` (Tibetan) first, probably understood by less than 0.5% of the population.

The second link mostly contains data from the CIA Factbook -- I notice minor variations but without a thorough review it can't be determined.

If memory serves me right, I manually cross-referred information from both, fixed some inaccuracies, performed some Wikipedia checks on the language populations to make this. There should not be any licensing problem.

In any case, let's change to use the CIA Factbook and Wikipedia as our official data sources.

Perhaps this mapping will be most useful if it is repurposed into a JSON with more information?

**Comment by skalee** [comment]
CSV is good for now, but yes, JSON or YML may be better if we're going to enhance it in some way.

**Comment by ronaldtse** [comment]
@skalee if you have a bit of time, we'd rather see it become a JSON sooner than later 😉 It should probably belong in a separate repo so others can use it too!

**Comment by skalee** [comment]
Regarding mapping quality:

For Poland, this mapping returns `pl` (Polish), `de-PL`, `yi` (Yiddish), which is certainly incorrect.

Everyone in Poland speaks Polish unless he is an immigrant. There are some ethnical groups which have their local languages (notably Silesians speak Silesian – `szl`, Kashubs speak Kashubian – `csb`, neither of them included on that list!, also Germans), but they are bi-lingual, and speak Polish fluently. Their languages are regional heritages and are difficult to understand for people living in other parts of Poland. Yiddish is a language of Jewish minority which is practically non-existent in today's Poland, and they also speak Polish. There is some German minority, but I believe they also speak Polish.

Polish is the only language universally understood in Poland. Furthermore, It's more likely that some randomly picked Pole will understand English or Russian rather than Yiddish, Silesian, or Kashubian. German is obviously somewhat popular but as a foreign language.

Both CIA World Factbook and Infoplease are more accurate on this topic:
* https://www.cia.gov/library/publications/the-world-factbook/fields/2098.html#pl
* https://www.infoplease.com/languages-spoken-each-country-world

**Comment by ronaldtse** [comment]
Great to know there are many places that can be improved, especially by people who actually live in the country. Again it points out that this is a complex subject that should be individually considered country by country.

**Comment by skalee** [comment]
Fixed in #46. Discussion on mapping quality continues in https://github.com/riboseinc/country_to_locales_mapping/issues/11.
