### ISSUE TITLE
Deletion of the LocaleNameMap

### ISSUE THREAD

**Issue by PeterTKY** [riboseinc/request_info#51]
I just realised that the LocaleNameMap has been deleted, but we are actually using it in our code. Is there a specific reason for deleting it? Or is it better to move it into a separate gem/repo? 

Related commits:
* 4301fbb8831c94587c25172a73f75f598640a91e
* 465e95d16d5bdf26bddc24dd01cb07aa95ebe501
* e11cda83dd04f5145dec5f77455caae512ad40b6

**Comment by ronaldtse** [comment]
@skalee I don’t remember why this was removed. Perhaps better to be in a separate repo? 

I think the use case of @PeterTKY is actually for JSON, maybe we can use the same structure for country-locale-map which we extracted?

**Comment by skalee** [comment]
@ronaldtse @PeterTKY I don't recall exactly, but some answer is here: #45, and here: #38.

I don't think it was in scope of this project. Perhaps copying class to another gem or to target application is a better idea? You'll find actual class definition in the aforementioned pull request.

I'll double check reasons behind removal that map tomorrow, got to go now.

**Comment by ronaldtse** [comment]
@skalee I think the main reason was that this data is already available in the Unicode CLDR and they do a good job of localizing language names. We can use the `twitter_cldr` gem to achieve this easily.

```ruby
irb(main):001:0> require 'twitter_cldr'
=> true
irb(main):002:0> :es.localize(:es).as_language_code
=> "español"
irb(main):003:0> :"zh-Hant".localize(:"zh-Hant").as_language_code
=> "繁體中文"
irb(main):004:0> :"ru".localize(:"ru").as_language_code
=> "русский"
```

Thanks!
